- name: Check all port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 2
    timeout: 3
  ignore_errors: yes
  register: port_out
  delegate_to: localhost
  tags: port_check


#- name: Port Failed Status
#  fail:
#    msg: "Port 22 is not Reachable"
#  when: port_out is failed
#  tags: port_check


- name: Port Success Status
  debug:
    msg: "Port 22 is Reachable"
  when: port_out is success
  tags: port_check

- name: create snapshot
  include: snap_create.yml
  vars:
       Instance_id: "{{ item.0 }}"
       Region: "{{ item.1 }}"
      # Tags: "{{ item.2 }}"
  with_together:
       - "{{ Instance_id }}"
       - "{{ Region }}"
      # - "{{ Tags }}"
  when: Instance_id is defined      

- name: create volume
  include: snap_vol_create.yml
  when: Volume_id is defined
  vars:
      Volume_id: "{{ vol.0 }}"
      Region: "{{ vol.1 }}"
      Tags: "{{ vol.2 }}"
  with_together:
     - "{{ Volume_id }}"
     - "{{ Region }}"
    # - "{{ tags }}
  loop_control:
         loop_var: vol










