- name: OS Flavor Check
  fail:
    msg: "OS VERSION NOT COMPATIBLE"
  when: ansible_distribution != "RedHat"
  tags: unittest

- name: Print output
  debug:
    msg: "OS Compatibility Check Completed "
  when: ansible_distribution == "RedHat"
  tags: unittest
