- name: Creating Snapshot
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars_files:
       - /ansible_playbooks/group_vars/aws_creds

  roles: 
    - snap

#https://ec2.ap-south-1b.amazonaws.com/
