- hosts: linux
  become_user: root
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
 
  vars_files:
       - /var/lib/jenkins/workspace/group_vars/aws_cred

  roles: 
    - snap
