- hosts: linux
  become_user: root
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.8
 
  vars_files:
       - /var/lib/jenkins/workspace/group_vars/aws_cred

  roles: 
    - snap
