pipeline {
  
   agent any
  
       stages {
         
         stage ('snap') {
           
           steps {
             
             sh 'ansible-playbook /var/lib/jenkins/workspace/${JOB_NAME}/Snapshot_del/Playbooks/snap.yml --vault-password-file=/var/lib/jenkins/workspace/vault_pass --extra-vars Instance_id=${Instance_id} --extra-vars Volume_id=${Volume_id} --extra-vars Region=${Region}'
           }
           
         }
         
       }
  
    }
